# Generated by Django 4.1.3 on 2023-01-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
