# Generated by Django 4.1.3 on 2023-01-09 06:52

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
                ('category', models.ManyToManyField(related_name='brand', to='pages.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name_plural': 'نام تجاری',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('discount_price', models.IntegerField(blank=True, null=True, verbose_name='درصد تخفیف')),
                ('slug', models.SlugField()),
                ('description', ckeditor.fields.RichTextField(default=' ', verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='static/img', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='موجودی')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='نام تجاری')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='pages.category')),
            ],
            options={
                'verbose_name_plural': 'محصول',
            },
        ),
        migrations.CreateModel(
            name='Commend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reply', models.BooleanField(default=False, verbose_name='پاسخ است')),
                ('body', ckeditor.fields.RichTextField(verbose_name='بدنه')),
                ('create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('active', models.BooleanField(default=False, verbose_name='فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='محصول')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_commend', to='products.commend', verbose_name='پاسخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name_plural': 'نظرات  محصول',
            },
        ),
    ]
