# Generated by Django 4.1.3 on 2022-12-22 06:38

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description_long',
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=ckeditor.fields.RichTextField(default=' ', verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(related_name='brand', to='pages.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=150, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='commend',
            name='active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='commend',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='بدنه'),
        ),
        migrations.AlterField(
            model_name='commend',
            name='create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='commend',
            name='is_reply',
            field=models.BooleanField(default=False, verbose_name='پاسخ است'),
        ),
        migrations.AlterField(
            model_name='commend',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='commend',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.commend', verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='commend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='نام تجاری'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='pages.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='static/img', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
