# Generated by Django 4.1.3 on 2023-01-09 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'آدرس ها',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='products.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name_plural': 'سبد خرید',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Auto dont input any thing', max_length=15, null=True)),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='مقدار')),
                ('min_order', models.IntegerField(blank=True, null=True, verbose_name='حداقل سفارش ')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('expiry', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ انتضا')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_in_coupon', related_query_name='related_query_coupon', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کد تخفیف ها ',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ خرید')),
                ('ordered_date', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ سفارش')),
                ('ordered', models.BooleanField(default=False, verbose_name='سفارش داده شده است')),
                ('address', models.CharField(max_length=500, verbose_name='آدرس')),
                ('received', models.BooleanField(default=False, verbose_name='تحویل داده شده')),
                ('refund_requested', models.BooleanField(default=False, verbose_name='درخواست بازگشت پول ')),
                ('refund_granted', models.BooleanField(default=False, verbose_name='درخواست پول انجام شده')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.coupon', verbose_name='کد تخفیف')),
                ('items', models.ManyToManyField(to='orders.cart', verbose_name='محصول')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment', verbose_name='پرداخت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربر')),
            ],
            options={
                'verbose_name_plural': 'سفارش',
            },
        ),
    ]
